# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, transformers, xhtml }:

cabal.mkDerivation (self: {
  pname = "tdoc";
  version = "0.4.6";
  src = ./.;
  buildDepends = [ transformers xhtml ];
  meta = {
    homepage = "https://github.com/np/tdoc";
    description = "TDoc is a typed document builder with support for (X)HTML";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
